### ISSUE TITLE
[Qeustion] Any drawbacks

### ISSUE THREAD

**Issue by krispetkov** [Michal-Stempkowski/TrueCompositionRootWithAspNetCore#1]
Hi there, 

First of all great approach, very clever way to accomplish true Clean Architecture!
I just wanted to ask you if you have found any drawbacks or quirks with this approach until now?
Or if you have found any similar solutions?
And have you tried to use it in production and what is the behavior?

Thanks in advance!

**Comment by Michal-Stempkowski** [comment]
Thanks. We are using it on production in my company for over a year and haven't encountered any drawbacks to this approach yet.

We were running it with MVC + jQuery, currently MVC + React app, with two composition roots (Main Component) setup. Same UI used in both, one with real backend, one with simplified and stubbed one for demo / prototyping / allowing frontend developers to start working on new features without backend being ready.

Haven't yet migrated to .NET Core 3.0, not sure if there is something out there that could impact this setup.

**Comment by krispetkov** [comment]
Hi, Thanks for your answer! I will give it a try with .Net Core 3.0 these days and will see if there are some differences. The only thing that I noticed is that if I'm using this approach when I run the project it does not start the browser automatically and I was wondering if there can be some difficulties with debugging the project (attaching the debugger etc.) but I haven't tested it yet.

**Comment by Michal-Stempkowski** [comment]
Well, this is interesting, we never encountered any issues with debugging and page starts automatically. At least in Visual Studio. Maybe I haven't ported some run configuration here or missed some settings in launchSettings.json. Are you running or publishing application? I will check it on the weekend, maybe I have added only publish definition or missed something else.

**Comment by krispetkov** [comment]
I'm just running it in debug from my Visual Studio 2019 and when it does start it opens the following console:

![Annotation 2020-02-26 225548](https://user-images.githubusercontent.com/6774998/75386919-289a9680-58eb-11ea-8af3-e54fc86a76fe.jpg)

And I have to manually open a web browser and navigate to some of the links showed in the console.
And another thing that I had to change in the code so the project can be started is that:

Old (Couldn't run the project):
`var webAbbDirectory = Path.Combine(parentDirectory, nameof(WebApp));`

New:
`var webAbbDirectory = Path.Combine(parentDirectory, "netcoreapp2.1");`

It's not a big deal just wanted to mention it. Maybe these problems comes from the Visual Studio because it's a newer version or something like that.

**Edit:**

I have tried this approach with .NET Core 3.1 but couldn't make it run. In versions >= 3.0 there is no **webhost** anymore but just a **host** and it throws:

**System.InvalidOperationException: 'Unable to resolve service for type 'Web.INonUiDependencyRegistry' while attempting to activate 'Web.Startup'.'**

You can see the project here: https://github.com/KrisPetkov/KrisComposition

**Comment by Michal-Stempkowski** [comment]
OK, so finally I had some time to look into this. So what's wrong:

> I'm just running it in debug from my Visual Studio 2019 and when it does start it opens the following console:

It would seem that I created that project as console app instead of web app, which could cause some issues here. Also when creating run definition from rider it does not open your browser by default it seems, you must select it in build configuration:

![launch_in_browser](https://user-images.githubusercontent.com/3198218/75812027-c67bde80-5d8d-11ea-8533-0efa8ccf1cb9.png)


![project_type](https://user-images.githubusercontent.com/3198218/75812171-0ba01080-5d8e-11ea-902c-fe7d9f7e69b7.png)

> Old (Couldn't run the project):
`var webAbbDirectory = Path.Combine(parentDirectory, nameof(WebApp));`

Yes, my bad. As described in README basic idea is here that we start application from CompositionRoot project rather than WebApp. Some things in ASP.NET MVC rely (don't remember right now whether in Configure() / ConfigureServices() / runtime ) on current directory. Had something to do with resource loading or sth, would need to test it to recall exactly.

So as to fixing current path - you have at least 2 scenarios. One - structure is flat (for example after release). Then you are already in correct directory (application binary is in the same folder as wwwroot). Second option is that you are not released but running for example from visual studio. Then you can be... somewhere. May depend on IDE / OS / some project settings. But in case of most projects we can assume as a rule of thumb that if wwwroot is not present in current dir, then we are in some nested directory, for example CompositionRoot/bin/Debug/netcoreapp3.1 or sth like that. We must change directory to proper one.

We can achieve that for example using simple loop, going up directories until you're in folder containing wwwroot. Then you are on top level, where web project resides. Going inside it should solve all potential problems (in solution present here we don't go down to /bin/Debug/etc... part, going to /WebApp seems enough, in case of some problems with resources maybe it would be better to go down to dir where WebApp.dll resides, but I am 90% sure that going to /WebApp is enough.

I recently have done commit adding that loop. Not sure how that was working - thanks for pointing that out. It tried going up only by one level. One of two things probably happened - either I tested only publish (flattened directory - no going up needed, everything worked) or Rider under MacOs creates only bin folder without /Debug/sth part and I didn't notice that because everything worked.

Anyway we need to get somehow to that web project directory. This loop based going up is quite universal, though may not be the best solution for production. On the other hand it is required only when running locally; released web project is flat. It works as POC, but in case of real life project I suggest different way of dealing with issue. If it occurs at all, there were several new versions of .NET Core, maybe it is no longer required.

I have just done update to this project. Currently it uses .NET Core 3.1 (as it is LTS) and everything seems to be working fine.

For example javascript debugging:

![javascript_debugging](https://user-images.githubusercontent.com/3198218/75815579-f7f7a880-5d93-11ea-889b-f63145f673f9.png)

> System.InvalidOperationException: 'Unable to resolve service for type 'Web.INonUiDependencyRegistry' while attempting to activate 'Web.Startup'.'

I will take a look at your project in a minute. It looks like missing registration. You need to register NonUiDependencyRegistry in your CompositionRoot (or whatever you called it, this is just the name that I came with, I mean that class that is responsible for registering all the non i dependencies). So it needs to be injected before Startup. I do it in the following lines:

`.ConfigureServices(services => services.AddSingleton<INonUiDependencyRegistry>(
                    provider => new NonUiDependencyRegistry()))`

at the Main method:

`static void Main(string[] args)
        {
            MoveToProperDirectory();
            WebHost
                .CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .ConfigureServices(services => services.AddSingleton<INonUiDependencyRegistry>(
                    provider => new NonUiDependencyRegistry()))
                .Build()
                .Run();
        }`

This way Startup knows nothing about those dependencies and this is what really allows us to separate UI and non-ui dependencies ;)

**Comment by Michal-Stempkowski** [comment]
After cloning your solution I encountered same issue that you described, even though I see that there is registration present, which is strange. On the other hand there was a little different order and methods used to construct builder, I changed it. Also you must run of course your "Startup" project, not "WebApp" (found run definitions for that second only).

Forked and created pull request which changes host builder used. Works for me. Remember to run Startup project, not the WebApp  ;) 
![2020-03-03 (5)](https://user-images.githubusercontent.com/3198218/75819720-70159c80-5d9b-11ea-86b0-b9bd9658a5db.png)

![2020-03-03 (6)](https://user-images.githubusercontent.com/3198218/75819737-73a92380-5d9b-11ea-86d7-1889fd415b76.png)

**Comment by krispetkov** [comment]
Thank you for your time and the detailed explanation, really helpful indeed!
I saw your PR and I will give it a try in few days when I get back home and will close the issue.
Thank you again!

**Comment by Michal-Stempkowski** [comment]
Ok, so regarding your finding about WebHost - you are totally right! I have forgotten that it was deprecated. Sorry for that. And the reason for that deprecation is quite important here!

So let's analyse it.

**Genesis of problem**

Microsoft wanted to have their WebHost extensible. So they allowed to register dependencies during building WebHost. When used properly it works nicely. However this feature seems not used a lot and when it is used then people often do not realise that it has some potential issues.

**So how this two-stage approach works (simplified)?**

Builder has separate DI container. When you register things like INonUiDependencyContainer, Startup etc. then we can reason about them as being registered to that container.

When we need to create startup class then it's being created together with its dependencies using that container. Then new container is being created and all dependencies that you register inside it are being registered to that new container. Application will use second container, first one is just for initialization purposes.

**Biggest problem with this approach**

What if you registered some things as singleton in first container? And then resolve them in second container? Well, whose are separate containers. Singleton gets created twice.

Notice that NonUiDependencyContainer is singleton. However it uses IServiceCollection passed to it from Startup class - so second container is being used to register all those dependencies specified in INonUiDependencyContainer. It itself is not used anymore in application. So no problems here, everything relevant registered in second container. And NonUiDependencyContainer is stateless. Not sure even why I registered it as singleton. However this could be problematic - if it at some point it became statefull or it was paramount for it to be created only once then we could have problem here.

I believe that many people that discovered that mechanism abused it to register multiple singleton dependencies that were singletons for a reason and then run into some strange, hard t reason about problems (at least until they got to know truth about that container duality, which could be potentially frustrating).

Problem better described here: https://andrewlock.net/avoiding-startup-service-injection-in-asp-net-core-3/ (link found on that microsoft page quoted by you, there are also some possible workarounds for several simple issues).

**So what Microsoft did?**

They disabled that possibility. When you reason about their app Startup is your CompositionRoot and you are stuck with that design.

**What should we do about it**

Maybe nothing. Fighting against design is usually bad idea. There might be better alternatives to deal with those issues, maybe some new mechanism in .NET Core 3 that allows us to deal better with dependency separation / substitution / multiple composition root setup. I would need to investigate. Though overall it seems unlikely - they want Startup to be their single place of truth, they propose using things like debug flags etc. if you need to differentiate sth.

**But can we do something about it?**

Well, we certainly can. I believe that there are at least several ways to deal with this issue. I will use the simplest and most straightforward way that comes to my mind - use old good reflection.

The only thing that we need that registrator for is to register some dependencies. It is already stateless and its usage is simple. It has an interface. It is default constructible.

So we can use reflection on Startup.cs side.

`
        private static void RegisterNonUiDependencies(IServiceCollection services)
        {
            var modules = AppDomain
                .CurrentDomain
                .GetAssemblies()
                .SelectMany(assembly => assembly.GetTypes())
                .Where(type => type.GetInterfaces().Contains(typeof(INonUiDependencyRegistry)))
                .Select(Activator.CreateInstance)
                .Cast<INonUiDependencyRegistry>();

            foreach (var module in modules)
            {
                module.RegisterAllNonUiDependencies(services);
            }
        }`

**Prons:**
- Simple?: especially as you do it once in startup, use created registrators and then can forget about them. I believe that this code is also pretty straightforward.
- Modularity?: I believe that we should rename our registrators - those no longer are registrators, rather modules. You can have many of those. Well, you could even define one per project if you wish. That way modules would descbe themselves, and you only need to reference appropriate assemblies.
- Extensibility?: you are using those registrators inside ConfigureServices method. You can do anything you want there - modules can have some attributes on which you can base their logic (decide in startup if you actually want to run them), you can read something from configuration and based on that register modules, use environment etc. Sky is the limit. But you should strive for simplicity and ease of use, not overcomplicating it like this. Current version should cover normal cases.
- Ease of creation? - new guy creating new module just needs to implement interface for this to work. If he does not make it default constructible - exception. You do not worry about its lifespan - localized to that method only

**Cons (potential?):**
- Simple?: may not cover all usecases, you need something more powerful and allowing different way to extend current solution. Though I think that it should not be issue and also you can introduce something more complicated then - when the need arises.
- Modularity? - maybe you do not want modules to describe themselves and have everything centralized. No problem - just replace "Where" with "Single" and include dependencies that all has one implementation of that interface. If you by accident will have two, then it will result in easy to understand error.
- Extensibility? - yes, this solution opens up many possibilities, so someone may over complicate things in future. For example do some strange things in module constructor. Or depend on the order of module registration. Add dependency that adds module that registers something that should not be registered. Yeah, there are always potential ways to mess something up. You can protect yourself in many different ways (for example tests with different module registration order etc.).
- Slowness? - not relevant here. It happens during initialization only. Unless you have tens of thousands types and need your web to be up and restarted under 1 second. However I believe that then this portion of code will be the least of your performance problems here ;) 
- Dependency is bad and magical? - it's either way used under hood of many different frameworks. Nothing magical happening here, no dynamic construction of type names, etc. If you don't like it then there should be other ways to solve that problem (some framework, maybe native Host support for sth, using static members etc.). This seemed like good enough solution to me, there might be much better solution out there.
- I cannot use dependency due to some constraints (hardware architecture does not allow me or sth)? - shouldn't be issue in 99% cases, also you will probably have bigger problems with .NET Core MVC to deal with than this small issue.

**Alternatives?**

- Some framework cooperating nicely with .NET Core that allows nice modularity. Don't know one (for example Prism allows module creation, but it's rather WPF, not sure about MVC in .NET Core, also such frameworks could be overkill here);
- Other possibilities mentioned in README;
- "Features" functionality in .NET Core. We did not decide on it due to some other issues, but it could also be used for separation of concerns, though I would investigate it thoroughly first;
- use static class members (statically initialize registrator);
- use static members (assignable to Action) in static classes with custom attribute [NonUiDependencyRegistrationFunction and retrieve them via reflection]. Could be more complicated, but module creators would be more restricted (they would be forced to create modules as static classes and have there static method registering things, so for example they cannot mess with constructor)
- many different ways;

**Comment by krispetkov** [comment]
Great explanation! Totally nailed it 🚀 
I will merge the PR and close the issue.
Thank you for your time!
